name: Publish to NPM

on:
  pull_request:
    types: [closed]
    branches:
      - '**'

jobs:
  create_tag_and_release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Configure Git credentials
      run: |
        git config --global user.email "alexalves2501@hotmail.com"
        git config --global user.name "github-actions[bot]"

    - name: Extract package version
      id: version
      run: echo ::set-output name=version::$(node -e "console.log(require('./package.json').version)")

    - name: Create tag
      run: git tag -a v${{ steps.version.outputs.version }} -m "Version ${{ steps.version.outputs.version }}"

    - name: Push tag to GitHub
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tags: v${{ steps.version.outputs.version }}

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: Release ${{ steps.version.outputs.version }}
        body: |
          Release ${{ steps.version.outputs.version }}
        draft: false
        prerelease: false
